apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tax-monolith
spec:
  hosts:
    - "*"
  gateways:
    - gateway
  http:
    - route:
      - destination:
          host: tax-monolith
          port:
            number: 80
      mirror:
        host: tax-service
        port:
          number: 80
